<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('10', '/uploads/allimg/121109/1-1211091513291.jpg');
$maNum = 1;
$myaddons[$maNum] = array('11', '/uploads/allimg/121109/1-1211091513302.jpg');
$maNum = 2;
$myaddons[$maNum] = array('12', '/uploads/allimg/121109/1-1211091513353.jpg');
$maNum = 3;
$myaddons[$maNum] = array('13', '/uploads/allimg/121109/1-1211091550574.jpg');
$maNum = 4;
$myaddons[$maNum] = array('14', '/uploads/allimg/121109/1-1211091551085.jpg');
$maNum = 5;
