<?php
$z[0]=Array("global","",147,172);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",185,214);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",269,295);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","<li><i class=\"left\"></i><i class=\"right\"></i><a href='[field:typeurl/]'><span>[field:lang.indexname/]</span></a></li>",481,639);
$z[3][4]['get']="index";
$z[4]=Array("channel","<li><i></i><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li> ",651,882);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='hover'><i></i><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>