<?php
$z[0]=Array("lang","",437,458);
$z[0][4]['name']="username";
$z[1]=Array("lang","",610,631);
$z[1][4]['name']="password";
$z[2]=Array("lang","",784,809);
$z[2][4]['name']="validatecode";
$z[3]=Array("global","",926,951);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("lang","",978,1003);
$z[4][4]['name']="validatecode";
$z[5]=Array("lang","",1121,1139);
$z[5][4]['name']="login";
$z[6]=Array("lang","",1251,1272);
$z[6][4]['name']="register";
$z[7]=Array("langlist","\r\n      <li><a href=\"[field:typeurl/]\" title=\"[field:langname/]\">[field:langname/]</a></li>\r\n    ",1477,1605);
$z[8]=Array("lang","",1641,1661);
$z[8][4]['name']="langent";

?>