<?php
$z[0]=Array("global","",147,172);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",185,214);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",269,295);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",535,560);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","<li><i></i><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li> ",603,834);
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='hover'><i></i><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>